apiVersion: v1
kind: Service
metadata:
  name: misp-modules
spec:
  selector:
    app: misp-modules
  ports:
    - port: 6666
      targetPort: 6666
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: misp-modules
spec:
  replicas: 1
  selector:
    matchLabels:
      app: misp-modules
  template:
    metadata:
      labels:
        app: misp-modules
    spec:
      containers:
        - name: misp-modules
          image: ghcr.io/misp/misp-docker/misp-modules:latest
          envFrom:
            - configMapRef:
                name: misp-configs
          volumeMounts:
            - name: action-mod
              mountPath: /custom/action_mod/
            - name: expansion
              mountPath: /custom/expansion/
            - name: export-mod
              mountPath: /custom/export_mod/
            - name: import-mod
              mountPath: /custom/import_mod/
          livenessProbe:
            exec:
              command:
                ["bash", "-c", "</dev/tcp/localhost/6666"]
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 1
            failureThreshold: 3
      volumes:
        - name: action-mod
          persistentVolumeClaim:
            claimName: misp-action-mod
        - name: expansion
          persistentVolumeClaim:
            claimName: misp-expansion
        - name: export-mod
          persistentVolumeClaim:
            claimName: misp-export-mod
        - name: import-mod
          persistentVolumeClaim:
            claimName: misp-import-mod