apiVersion: v1
kind: Service
metadata:
  name: misp-core
spec:
  type: LoadBalancer
  selector:
    app: misp-core
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443